### ISSUE TITLE
Return NULL instead of NA when field does not exist

### ISSUE THREAD

**Issue by lionel-** [metacran/desc#25]
In R `NA` is the presence of an absence, `NULL` the absence of a presence (ancient Hadley proverb).

It'd make more sense to return `NULL` when a field is not existing. Also it'd prevent weird code. For testing absent fields we'd have:

```r
note <- desc$get("myfield")

if (is.null(note))
```

instead of

```r
if (identical(note, c(myfield = NA_character_)))
```

**Comment by gaborcsardi** [comment]
Unfortunately that's not possible because `get` is vectorized: 

```
❯ desc::desc_get(c("Package", "myfield", "Title"))
                               Package                                myfield
                            "processx"                                     NA
                                 Title
"Execute and Control System Processes"
```

If you query a single field, then I think you can use `is.na` instead of `identical`, no?

**Comment by lionel-** [comment]
Indeed I initially thought that desc would return vectors of length > 1 for components like authors but I see that's not the case.
