### ISSUE TITLE
Alias desc to description$new()

### ISSUE THREAD

**Issue by hadley** [metacran/desc#30]
So you can do `desc::desc(path)` (which is what I try and do every time I use the package)

Would be even nicer to make it

```R
desc <- function(path, name = "DESCRIPTION") { 
  description$new(file.path(path, name))
}
```

Or since it's just a helper and won't be needed for testing, just provide the path.

**Comment by gaborcsardi** [comment]
I don't mind this, but isn't it usually simpler to just use the non-OO API, so that you don't need to create any objects at all: 
```r
❯ desc::desc_get_urls()
#> [1] "https://github.com/gaborcsardi/debugme#readme"
❯ desc::desc_get_urls(".")
#> [1] "https://github.com/gaborcsardi/debugme#readme"
```

If you need to create an object , then you can also write 
```r
❯ desc::description$new(".")
#> Package: debugme
#> Title: Debug R Packages
```

But anyway, yes, I can add this. The package was originally called `description`, hence the different class name, but then I had to rename it.

**Comment by hadley** [comment]
I'm currently doing this to turn the description into a list which I can feed to whisker:

```R
package_data <- function(base_path = ".") {
  desc_path <- file.path(base_path, "DESCRIPTION")

  desc <- desc::description$new(desc_path)
  as.list(desc$get(desc$fields()))
}
```

**Comment by hadley** [comment]
Using desc is probably overkill here, but I figure at some point I'm likely to want to include authors etc in the template data.

**Comment by gaborcsardi** [comment]
I see. I remember being annoyed having to type `desc::description:$new()`, so `desc::desc` will be good.

Btw. `desc` should probably also have a method that just converts to a list.... `desc::desc_get(desc::desc_fields())` does that, but still....
